const careerLevels = [
    "No Qualification",
    "5th Pass",
    "8th Pass",
    "10th Pass",
    "ITI",
    "Diploma",
    "12th Pass",
    "Graduate",
    "Post Graduate",
    "Professional",
    "Team Lead",
    "Supervisor",
    "Manager",
    "Senior Manager",
    "General Manager",
    "Director",
    "Vice President",
    "President",
    "COO",
    "CFO",
    "CTO",
    "CEO"
];
