// languages-kannada.js - Kannada (ಕನ್ನಡ) translations

if (typeof translations === 'undefined') {
    var translations = {};
}

translations.kn = {
    app_name: "ದಿಲ್ ಕೆ ಅನ್ಷ್",
    app_tagline: "ದಿಲ್-ಕೆ-ಅನ್ಷ್ ಕರಿಯರ್ ಸಾಥಿ",
    tagline: "ಅನಾಮಧೇಯವಾಗಿ ಓದು, ಬಿಂದಾಸ್ ಆಗಿರು",
    welcome: "ಮತ್ತೆ ಸ್ವಾಗತ, ವಿದ್ಯಾರ್ಥಿ!",
    search_placeholder: "ಕೋರ್ಸ್ಗಳು, ಪರೀಕ್ಷೆಗಳು, ಉದ್ಯೋಗಗಳು, ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ...",
    ask_ai: "AnnS AI ಕೇಳಿ",
    back: "ಹಿಂದೆ",
    choose_stream: "ನಿಮ್ಮ ಸ್ಟ್ರೀಮ್ ಆಯ್ಕೆಮಾಡಿ",
    coming_soon: "ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ",
    bottom_home: "ಮುಖಪುಟ",
    bottom_search: "ಹುಡುಕು",
    bottom_ai: "AnnS AI",
    bottom_alerts: "ಎಚ್ಚರಿಕೆಗಳು",
    bottom_profile: "ಪ್ರೊಫೈಲ್",
    explore_title: "ವೃತ್ತಿ ಮಾರ್ಗಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
    education: "ಶಿಕ್ಷಣ",
    business: "ವ್ಯಾಪಾರ",
    jobs_exams: "ಉದ್ಯೋಗಗಳು ಮತ್ತು ಪರೀಕ್ಷೆಗಳು",
    study_material: "ಅಧ್ಯಯನ ಸಾಮಗ್ರಿ",
    magazines: "ನಿಯತಕಾಲಿಕೆಗಳು",
    enewspapers: "ಇ-ಪತ್ರಿಕೆಗಳು",
    current_affairs: "ದೈನಂದಿನ ಪ್ರಸ್ತುತ ವಿದ್ಯಮಾನಗಳು",
    mock_test: "ಮಾಕ್ ಟೆಸ್ಟ್",
    after_10th: "10ನೇ ತರಗತಿ ನಂತರ",
    after_12th: "12ನೇ ತರಗತಿ ನಂತರ",
    something_interesting: "ಆಸಕ್ತಿದಾಯಕ ಸಂಗತಿಗಳು",
    results: "ಫಲಿತಾಂಶಗಳು ಮತ್ತು ಕಟ್-ಆಫ್",
    application_forms: "ಅರ್ಜಿ ನಮೂನೆಗಳು",
    bharat: "ಭಾರತ್",
    education_streams: "ಶಿಕ್ಷಣ ವಿಭಾಗಗಳು",
    medical: "ವೈದ್ಯಕೀಯ",
    non_medical: "ವೈದ್ಯಕೀಯೇತರ",
    commerce: "ವಾಣಿಜ್ಯ",
    arts: "ಕಲೆಗಳು",
    sports: "ಕ್ರೀಡೆ",
    agriculture: "ಕೃಷಿ",
    artist: "ಕಲಾವಿದ",
    designing: "ವಿನ್ಯಾಸ",
    skilled: "ಕೌಶಲ್ಯ",
    abroad: "ವಿದೇಶ",
    medical_title: "ವೈದ್ಯಕೀಯ ಮತ್ತು ಆರೋಗ್ಯ ವೃತ್ತಿಗಳು",
    mbbs: "ಎಂಬಿಬಿಎಸ್ – ವೈದ್ಯಕೀಯ ಪದವಿ",
    entrance_exams: "ಪ್ರವೇಶ ಪರೀಕ್ಷೆಗಳು",
    neet: "ನೀಟ್ – ರಾಷ್ಟ್ರೀಯ ಅರ್ಹತಾ ಪ್ರವೇಶ ಪರೀಕ್ಷೆ",
    govt_jobs: "ವೈದ್ಯಕೀಯ ನಂತರ ಸರ್ಕಾರಿ ಉದ್ಯೋಗಗಳು",
    bharat_title: "ಭಾರತ್ – ನಿಮ್ಮ ದೇಶವನ್ನು ತಿಳಿದುಕೊಳ್ಳಿ",
    constitution: "ಭಾರತೀಯ ಸಂವಿಧಾನ",
    fundamental_rights: "ಮೂಲಭೂತ ಹಕ್ಕುಗಳು",
    ipc: "ಭಾರತೀಯ ದಂಡ ಸಂಹಿತೆ (ಐಪಿಸಿ)",
    legal_rights: "ಕಾನೂನು ಹಕ್ಕುಗಳು",
    police_dealing: "ಪೊಲೀಸರೊಂದಿಗೆ ಹೇಗೆ ವ್ಯವಹರಿಸಬೇಕು",
    emergency_helplines: "ತುರ್ತು ಸಹಾಯವಾಣಿಗಳು",
    pro_writing: "ಪ್ರೋ ರೈಟಿಂಗ್ ಅಸಿಸ್ಟೆಂಟ್",
    essay_writer: "AI ಪ್ರಬಂಧ ಬರಹಗಾರ",
    resume_builder: "ರೆಸ್ಯೂಮ್ ಬಿಲ್ಡರ್",
    grammar_check: "ವ್ಯಾಕರಣ ಪರಿಶೀಲಕ"
};

console.log('Kannada language loaded');
