// languages-bengali.js - Bengali (বাংলা) translations

if (typeof translations === 'undefined') {
    var translations = {};
}

translations.bn = {
    app_name: "দিল কে আনশ",
    app_tagline: "দিল-কে-আনশ ক্যারিয়ার সাথী",
    tagline: "বেনামে পড়ো, বিন্দাস বোনো",
    welcome: "ফিরে আসার জন্য স্বাগতম, শিক্ষার্থী!",
    search_placeholder: "কোর্স, পরীক্ষা, চাকরি, প্রকল্প খুঁজুন...",
    ask_ai: "AnnS AI কে জিজ্ঞাসা করুন",
    back: "পিছনে",
    choose_stream: "আপনার স্ট্রিম নির্বাচন করুন",
    coming_soon: "শীঘ্রই আসছে",
    bottom_home: "হোম",
    bottom_search: "অনুসন্ধান",
    bottom_ai: "AnnS AI",
    bottom_alerts: "সতর্কতা",
    bottom_profile: "প্রোফাইল",
    explore_title: "ক্যারিয়ার পথ অন্বেষণ করুন",
    education: "শিক্ষা",
    business: "ব্যবসা",
    jobs_exams: "চাকরি ও পরীক্ষা",
    study_material: "পাঠ্য সামগ্রী",
    magazines: "ম্যাগাজিন",
    enewspapers: "ই-সংবাদপত্র",
    current_affairs: "দৈনিক কারেন্ট অ্যাফেয়ার্স",
    mock_test: "মক টেস্ট",
    after_10th: "১০ম শ্রেণির পরে",
    after_12th: "১২শ শ্রেণির পরে",
    something_interesting: "আকর্ষণীয় কিছু",
    results: "ফলাফল ও কাটঅফ",
    application_forms: "আবেদন ফর্ম",
    bharat: "ভারত",
    education_streams: "শিক্ষা শাখা",
    medical: "মেডিকেল",
    non_medical: "অ-মেডিকেল",
    commerce: "কমার্স",
    arts: "আর্টস",
    sports: "ক্রীড়া",
    agriculture: "কৃষি",
    artist: "শিল্পী",
    designing: "ডিজাইনিং",
    skilled: "দক্ষ",
    abroad: "বিদেশ",
    medical_title: "মেডিকেল ও স্বাস্থ্যসেবা ক্যারিয়ার",
    mbbs: "এমবিবিএস – মেডিসিন ও সার্জারি ডিগ্রি",
    entrance_exams: "ভর্তি পরীক্ষা",
    neet: "নীট – জাতীয় যোগ্যতা ভর্তি পরীক্ষা",
    govt_jobs: "মেডিকেলের পরে সরকারি চাকরি",
    bharat_title: "ভারত – আপনার দেশকে জানুন",
    constitution: "ভারতের সংবিধান",
    fundamental_rights: "মৌলিক অধিকার",
    ipc: "ভারতীয় দণ্ডবিধি (আইপিসি)",
    legal_rights: "আইনি অধিকার",
    police_dealing: "পুলিশের সাথে কীভাবে মোকাবিলা করবেন",
    emergency_helplines: "জরুরি হেল্পলাইন",
    pro_writing: "প্রো রাইটিং অ্যাসিস্ট্যান্ট",
    essay_writer: "এআই প্রবন্ধ লেখক",
    resume_builder: "রেজুমি বিল্ডার",
    grammar_check: "ব্যাকরণ পরীক্ষক"
};

console.log('Bengali language loaded');
