// languages-odia.js - Odia (ଓଡ଼ିଆ) translations

if (typeof translations === 'undefined') {
    var translations = {};
}

translations.or = {
    app_name: "ଦିଲ କେ ଅନ୍ସ",
    app_tagline: "ଦିଲ-କେ-ଅନ୍ସ କ୍ୟାରିୟର ସାଥୀ",
    tagline: "ଅଜ୍ଞାତ ଭାବରେ ପଢ, ବିନ୍ଦାସ୍ ହୁଅ",
    welcome: "ଫେରିଥିବାରୁ ସ୍ୱାଗତ, ଶିକ୍ଷାର୍ଥୀ!",
    search_placeholder: "କୋର୍ସ, ପରୀକ୍ଷା, ଚାକିରି, ଯୋଜନା ଖୋଜ...",
    ask_ai: "AnnS AI କୁ ପଚାର",
    back: "ପଛକୁ",
    choose_stream: "ତୁମର ସ୍ଟ୍ରିମ୍ ଚୟନ କର",
    coming_soon: "ଶୀଘ୍ର ଆସୁଛି",
    bottom_home: "ହୋମ",
    bottom_search: "ଖୋଜ",
    bottom_ai: "AnnS AI",
    bottom_alerts: "ସତର୍କତା",
    bottom_profile: "ପ୍ରୋଫାଇଲ",
    explore_title: "କ୍ୟାରିୟର ପଥ ଅନୁସନ୍ଧାନ କର",
    education: "ଶିକ୍ଷା",
    business: "ବ୍ୟବସାୟ",
    jobs_exams: "ଚାକିରି ଏବଂ ପରୀକ୍ଷା",
    study_material: "ଅଧ୍ୟୟନ ସାମଗ୍ରୀ",
    magazines: "ପତ୍ରିକା",
    enewspapers: "ଇ-ଖବରକାଗଜ",
    current_affairs: "ଦୈନିକ କରେଣ୍ଟ ଆଫେୟାର୍ସ",
    mock_test: "ମକ୍ ଟେଷ୍ଟ",
    after_10th: "୧୦ମ ପରେ",
    after_12th: "୧୨ଶ ପରେ",
    something_interesting: "କିଛି ରୋଚକ",
    results: "ଫଳାଫଳ ଏବଂ କଟଅଫ",
    application_forms: "ଆବେଦନ ଫର୍ମ",
    bharat: "ଭାରତ",
    education_streams: "ଶିକ୍ଷା ବିଭାଗ",
    medical: "ମେଡିକାଲ",
    non_medical: "ନନ୍-ମେଡିକାଲ",
    commerce: "କମର୍ସ",
    arts: "ଆର୍ଟସ୍",
    sports: "ଖେଳ",
    agriculture: "କୃଷି",
    artist: "କଳାକାର",
    designing: "ଡିଜାଇନିଂ",
    skilled: "କୁଶଳ",
    abroad: "ବିଦେଶ",
    medical_title: "ମେଡିକାଲ ଏବଂ ସ୍ୱାସ୍ଥ୍ୟ ସେବା କ୍ୟାରିୟର",
    mbbs: "ଏମବିବିଏସ – ମେଡିସିନ ଏବଂ ସର୍ଜରୀ ଡିଗ୍ରୀ",
    entrance_exams: "ପ୍ରବେଶ ପରୀକ୍ଷା",
    neet: "ନୀଟ – ଜାତୀୟ ଯୋଗ୍ୟତା ପ୍ରବେଶ ପରୀକ୍ଷା",
    govt_jobs: "ମେଡିକାଲ ପରେ ସରକାରୀ ଚାକିରି",
    bharat_title: "ଭାରତ – ତୁମର ଦେଶକୁ ଜାଣ",
    constitution: "ଭାରତର ସମ୍ବିଧାନ",
    fundamental_rights: "ମୌଳିକ ଅଧିକାର",
    ipc: "ଭାରତୀୟ ଦଣ୍ଡ ସଂହିତା (ଆଇପିସି)",
    legal_rights: "ଆଇନଗତ ଅଧିକାର",
    police_dealing: "ପୋଲିସ ସହିତ କିପରି ବ୍ୟବହାର କରିବେ",
    emergency_helplines: "ଜରୁରୀକାଳୀନ ସହାୟତା ଲାଇନ",
    pro_writing: "ପ୍ରୋ ରାଇଟିଂ ସହାୟକ",
    essay_writer: "AI ପ୍ରବନ୍ଧ ଲେଖକ",
    resume_builder: "ରେଜ୍ୟୁମେ ବିଲ୍ଡର",
    grammar_check: "ବ୍ୟାକରଣ ଯାଞ୍ଚକାରୀ"
};

console.log('Odia language loaded');
