// languages-tamil.js - Tamil (தமிழ்) translations

if (typeof translations === 'undefined') {
    var translations = {};
}

translations.ta = {
    app_name: "தில் கே அன்ஷ்",
    app_tagline: "தில்-கே-அன்ஷ் கரியர் சாதி",
    tagline: "அனானிமஸ் படி, பிந்தாஸ் பண்ணு",
    welcome: "மீண்டும் வரவேற்கிறோம், கற்பவரே!",
    search_placeholder: "படிப்புகள், தேர்வுகள், வேலைகள், திட்டங்களைத் தேடு...",
    ask_ai: "AnnS AI ஐ கேளுங்கள்",
    back: "பின் செல்",
    choose_stream: "உங்கள் பிரிவைத் தேர்வு செய்யுங்கள்",
    coming_soon: "விரைவில் வரும்",
    bottom_home: "முகப்பு",
    bottom_search: "தேடுக",
    bottom_ai: "AnnS AI",
    bottom_alerts: "அலர்ட்கள்",
    bottom_profile: "சுயவிவரம்",
    explore_title: "வாழ்க்கை பாதைகளை ஆராயுங்கள்",
    education: "கல்வி",
    business: "வணிகம்",
    jobs_exams: "வேலைகள் & தேர்வுகள்",
    study_material: "படிப்பு பொருட்கள்",
    magazines: "பத்திரிகைகள்",
    enewspapers: "மின்-செய்தித்தாள்கள்",
    current_affairs: "தற்போதைய நிகழ்வுகள்",
    mock_test: "மாதிரி தேர்வு",
    after_10th: "10 ஆம் வகுப்பிற்கு பின்",
    after_12th: "12 ஆம் வகுப்பிற்கு பின்",
    something_interesting: "சுவாரஸ்யமானவை",
    results: "முடிவுகள் & கட்-ஆஃப்",
    application_forms: "விண்ணப்ப படிவங்கள்",
    bharat: "பாரத்",
    education_streams: "கல்விப் பிரிவுகள்",
    medical: "மருத்துவம்",
    non_medical: "மருத்துவம் அல்லாத",
    commerce: "வணிகவியல்",
    arts: "கலைகள்",
    sports: "விளையாட்டு",
    agriculture: "வேளாண்மை",
    artist: "கலைஞர்",
    designing: "வடிவமைப்பு",
    skilled: "திறமையான",
    abroad: "வெளிநாடு",
    medical_title: "மருத்துவ & சுகாதார பாதுகாப்பு வாழ்க்கை",
    mbbs: "எம்பிபிஎஸ் – மருத்துவம் & அறுவை சிகிச்சை பட்டப்படிப்பு",
    entrance_exams: "நுழைவுத் தேர்வுகள்",
    neet: "நீட் – தேசிய தகுதி நுழைவுத் தேர்வு",
    govt_jobs: "மருத்துவத்திற்குப் பின் அரசு வேலைகள்",
    bharat_title: "பாரத் – உங்கள் நாட்டை அறிந்து கொள்ளுங்கள்",
    constitution: "இந்திய அரசியலமைப்பு",
    fundamental_rights: "அடிப்படை உரிமைகள்",
    ipc: "இந்திய தண்டனைச் சட்டம் (ஐபிசி)",
    legal_rights: "சட்ட உரிமைகள்",
    police_dealing: "காவல்துறையினருடன் எவ்வாறு நடந்துகொள்வது",
    emergency_helplines: "அவசர உதவி எண்கள்",
    pro_writing: "ப்ரோ ரைட்டிங் உதவியாளர்",
    essay_writer: "AI கட்டுரை எழுத்தாளர்",
    resume_builder: "மீண்டும் தொடங்கு கட்டமைப்பாளர்",
    grammar_check: "இலக்கண சரிபார்ப்பு"
};

console.log('Tamil language loaded');
