// languages-telugu.js - Telugu (తెలుగు) translations

if (typeof translations === 'undefined') {
    var translations = {};
}

translations.te = {
    app_name: "దిల్ కే అన్ష్",
    app_tagline: "దిల్-కే-అన్ష్ కెరీర్ సాథీ",
    tagline: "అనామకంగా చదువు, బిందాస్ గా ఉండు",
    welcome: "తిరిగి స్వాగతం, విద్యార్థీ!",
    search_placeholder: "కోర్సులు, పరీక్షలు, ఉద్యోగాలు, పథకాలను వెతకండి...",
    ask_ai: "AnnS AI ను అడగండి",
    back: "వెనుకకు",
    choose_stream: "మీ స్ట్రీమ్ ఎంచుకోండి",
    coming_soon: "త్వరలో రానున్నది",
    bottom_home: "హోమ్",
    bottom_search: "వెతకండి",
    bottom_ai: "AnnS AI",
    bottom_alerts: "హెచ్చరికలు",
    bottom_profile: "ప్రొఫైల్",
    explore_title: "కెరీర్ మార్గాలను అన్వేషించండి",
    education: "విద్య",
    business: "వ్యాపారం",
    jobs_exams: "ఉద్యోగాలు & పరీక్షలు",
    study_material: "స్టడీ మెటీరియల్",
    magazines: "మ్యాగజైన్లు",
    enewspapers: "ఈ-వార్తాపత్రికలు",
    current_affairs: "దైనందిన కరెంట్ అఫైర్స్",
    mock_test: "మాక్ టెస్ట్",
    after_10th: "10వ తరగతి తర్వాత",
    after_12th: "12వ తరగతి తర్వాత",
    something_interesting: "ఏదైనా ఆసక్తికరం",
    results: "ఫలితాలు & కటాఫ్",
    application_forms: "దరఖాస్తు ఫారాలు",
    bharat: "భారత్",
    education_streams: "విద్యా విభాగాలు",
    medical: "మెడికల్",
    non_medical: "నాన్-మెడికల్",
    commerce: "కామర్స్",
    arts: "ఆర్ట్స్",
    sports: "స్పోర్ట్స్",
    agriculture: "వ్యవసాయం",
    artist: "ఆర్టిస్ట్",
    designing: "డిజైనింగ్",
    skilled: "స్కిల్డ్",
    abroad: "విదేశం",
    medical_title: "మెడికల్ & హెల్త్కేర్ కెరీర్లు",
    mbbs: "ఎంబీబీఎస్ – మెడిసిన్ & సర్జరీ డిగ్రీ",
    entrance_exams: "ప్రవేశ పరీక్షలు",
    neet: "నీట్ – నేషనల్ ఎలిజిబిలిటీ కమ్ ఎంట్రన్స్ టెస్ట్",
    govt_jobs: "మెడికల్ తర్వాత ప్రభుత్వ ఉద్యోగాలు",
    bharat_title: "భారత్ – మీ దేశాన్ని తెలుసుకోండి",
    constitution: "భారత రాజ్యాంగం",
    fundamental_rights: "ప్రాథమిక హక్కులు",
    ipc: "భారతీయ శిక్షా స్మృతి (ఐపీసీ)",
    legal_rights: "చట్టపరమైన హక్కులు",
    police_dealing: "పోలీసులతో ఎలా వ్యవహరించాలి",
    emergency_helplines: "అత్యవసర హెల్ప్లైన్లు",
    pro_writing: "ప్రో రైటింగ్ అసిస్టెంట్",
    essay_writer: "AI వ్యాస రచయిత",
    resume_builder: "రెజ్యూమ్ బిల్డర్",
    grammar_check: "వ్యాకరణ తనిఖీ"
};

console.log('Telugu language loaded');
