// languages-punjabi.js - Punjabi (ਪੰਜਾਬੀ) translations

if (typeof translations === 'undefined') {
    var translations = {};
}

translations.pa = {
    app_name: "ਦਿਲ ਕੇ ਅੰਨ੍ਸ",
    app_tagline: "ਦਿਲ-ਕੇ-ਅੰਨ੍ਸ ਕੈਰੀਅਰ ਸਾਥੀ",
    tagline: "ਅਗਿਆਤ ਪੜ੍ਹੋ, ਬਿੰਦਾਸ ਬਣੋ",
    welcome: "ਵਾਪਸੀ ਤੇ ਸੁਆਗਤ ਹੈ, ਵਿਦਿਆਰਥੀ!",
    search_placeholder: "ਕੋਰਸ, ਪ੍ਰੀਖਿਆਵਾਂ, ਨੌਕਰੀਆਂ, ਯੋਜਨਾਵਾਂ ਖੋਜੋ...",
    ask_ai: "AnnS AI ਨੂੰ ਪੁੱਛੋ",
    back: "ਪਿੱਛੇ",
    choose_stream: "ਆਪਣਾ ਸਟ੍ਰੀਮ ਚੁਣੋ",
    coming_soon: "ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ",
    bottom_home: "ਹੋਮ",
    bottom_search: "ਖੋਜ",
    bottom_ai: "AnnS AI",
    bottom_alerts: "ਚੇਤਾਵਨੀਆਂ",
    bottom_profile: "ਪ੍ਰੋਫਾਈਲ",
    explore_title: "ਕੈਰੀਅਰ ਦੇ ਰਾਹ ਖੋਜੋ",
    education: "ਸਿੱਖਿਆ",
    business: "ਕਾਰੋਬਾਰ",
    jobs_exams: "ਨੌਕਰੀਆਂ ਅਤੇ ਪ੍ਰੀਖਿਆਵਾਂ",
    study_material: "ਅਧਿਐਨ ਸਮੱਗਰੀ",
    magazines: "ਮੈਗਜ਼ੀਨ",
    enewspapers: "ਈ-ਅਖਬਾਰ",
    current_affairs: "ਰੋਜ਼ਾਨਾ ਕਰੰਟ ਅਫੇਅਰਜ਼",
    mock_test: "ਮੌਕ ਟੈਸਟ",
    after_10th: "10ਵੀਂ ਤੋਂ ਬਾਅਦ",
    after_12th: "12ਵੀਂ ਤੋਂ ਬਾਅਦ",
    something_interesting: "ਕੁਝ ਦਿਲਚਸਪ",
    results: "ਨਤੀਜੇ ਅਤੇ ਕਟਆਫ",
    application_forms: "ਅਰਜ਼ੀ ਫਾਰਮ",
    bharat: "ਭਾਰਤ",
    education_streams: "ਸਿੱਖਿਆ ਦੇ ਖੇਤਰ",
    medical: "ਮੈਡੀਕਲ",
    non_medical: "ਨਾਨ-ਮੈਡੀਕਲ",
    commerce: "ਕਾਮਰਸ",
    arts: "ਆਰਟਸ",
    sports: "ਖੇਡਾਂ",
    agriculture: "ਖੇਤੀਬਾੜੀ",
    artist: "ਕਲਾਕਾਰ",
    designing: "ਡਿਜ਼ਾਈਨਿੰਗ",
    skilled: "ਹੁਨਰਮੰਦ",
    abroad: "ਵਿਦੇਸ਼",
    medical_title: "ਮੈਡੀਕਲ ਅਤੇ ਸਿਹਤ ਸੰਭਾਲ ਕੈਰੀਅਰ",
    mbbs: "ਐਮਬੀਬੀਐਸ – ਮੈਡੀਸਨ ਅਤੇ ਸਰਜਰੀ ਡਿਗਰੀ",
    entrance_exams: "ਪ੍ਰਵੇਸ਼ ਪ੍ਰੀਖਿਆਵਾਂ",
    neet: "ਨੀਟ – ਰਾਸ਼ਟਰੀ ਯੋਗਤਾ ਪ੍ਰਵੇਸ਼ ਟੈਸਟ",
    govt_jobs: "ਮੈਡੀਕਲ ਤੋਂ ਬਾਅਦ ਸਰਕਾਰੀ ਨੌਕਰੀਆਂ",
    bharat_title: "ਭਾਰਤ – ਆਪਣੇ ਦੇਸ਼ ਨੂੰ ਜਾਣੋ",
    constitution: "ਭਾਰਤ ਦਾ ਸੰਵਿਧਾਨ",
    fundamental_rights: "ਮੌਲਿਕ ਅਧਿਕਾਰ",
    ipc: "ਭਾਰਤੀ ਦੰਡ ਸੰਹਿਤਾ (ਆਈਪੀਸੀ)",
    legal_rights: "ਕਾਨੂੰਨੀ ਅਧਿਕਾਰ",
    police_dealing: "ਪੁਲਿਸ ਨਾਲ ਕਿਵੇਂ ਪੇਸ਼ ਆਉਣਾ ਹੈ",
    emergency_helplines: "ਐਮਰਜੈਂਸੀ ਹੈਲਪਲਾਈਨ",
    pro_writing: "ਪ੍ਰੋ ਰਾਈਟਿੰਗ ਸਹਾਇਕ",
    essay_writer: "AI ਲੇਖ ਲੇਖਕ",
    resume_builder: "ਰੈਜ਼
